Feat/usage rework
DistributedCollective/sovryn-monorepo pull request #20
Opened 2021-07-09 06:39 UTC by rick23p

Don't merge this yet!

2021-07-19 09:18 UTC, grinry requested changes

2021-07-19 09:18 UTC, grinry commented on packages/react-wallet/src/contexts/WalletContext.ts
> +import { FullWallet, ProviderType, WalletService } from '../../../wallet/dist';
```suggestion
import { FullWallet, ProviderType, WalletService } from '@sovryn/wallet';
```
Packages will not compile for publishing otherwise

2021-07-22 08:14 UTC, creed-victor approved these changes

2021-07-22 09:04 UTC, creed-victor requested changes
Ok, added new package version to https://github.com/DistributedCollective/Sovryn-frontend/pull/1475 - flow for (babelfish) deposits / withdrawals looks nice, however it broke other "engage wallet" flows which uses dialog. Clicking engage wallet opens dialog but user can scroll down of it, there is no overlay too (or it's indexed below header). 
Also, if user is scrolled down and clicks "engage wallet" - dialog appears at the of the document and is not visible to user until he scrolls back.
And I think dialog enter/exit transitions doesn't appear for the first interaction.

2021-07-22 17:19 UTC, ShynRou commented
@creed-victor fixed it.

2021-07-27 06:26 UTC, creed-victor approved these changes

2021-07-27 06:27 UTC, merged